
import 'package:appmanager/models/notification/notificationModel.dart';

List<notificationModel> notificationData = [
  notificationModel(title: "Ứng dụng di động Payoneer được hỗ trợ trên thiết bị nào?",
      suptitle: "Ứng dụng di động Payoneer hiện được hỗ trợ trên các thiết bị iOS và Android. Bạn có thể sử dụng các liên kết này để tải ứng dụng cho thiết bị của mình: iOS, Android.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "TTôi có thể thực hiện những thao tác nào với ứng dụng di động?",
      suptitle: " Ứng dụng di động Payoneer cho phép bạn dễ dàng quản lý tài khoản Payoneer của mình mọi lúc mọi nơi. Bạn có thể nhanh chóng kiểm tra tất cả số dư tài khoản hoặc thẻ, cũng như các giao dịch mới nhất của bạn, từ trang chủ của ứng dụng.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Làm cách nào để xem chi tiết và giao dịch cho một số dư cụ thể?",
      suptitle: "Từ Trang chủ, bấm vào bất kỳ tài khoản số dư nào của bạn để xem chi tiết số dư và các giao dịch mới nhất cho số dư đó. Để xem tất cả các giao dịch cho một số dư cụ thể, hãy nhấn Giao dịch trong menu và lọc theo số dư mong muốn.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Ứng dụng di động Payoneer được hỗ trợ trên thiết bị nào?",
      suptitle: "Ứng dụng di động Payoneer hiện được hỗ trợ trên các thiết bị iOS và Android. Bạn có thể sử dụng các liên kết này để tải ứng dụng cho thiết bị của mình: iOS, Android.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "TTôi có thể thực hiện những thao tác nào với ứng dụng di động?",
      suptitle: " Ứng dụng di động Payoneer cho phép bạn dễ dàng quản lý tài khoản Payoneer của mình mọi lúc mọi nơi. Bạn có thể nhanh chóng kiểm tra tất cả số dư tài khoản hoặc thẻ, cũng như các giao dịch mới nhất của bạn, từ trang chủ của ứng dụng.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Làm cách nào để xem chi tiết và giao dịch cho một số dư cụ thể?",
      suptitle: "Từ Trang chủ, bấm vào bất kỳ tài khoản số dư nào của bạn để xem chi tiết số dư và các giao dịch mới nhất cho số dư đó. Để xem tất cả các giao dịch cho một số dư cụ thể, hãy nhấn Giao dịch trong menu và lọc theo số dư mong muốn.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Ứng dụng di động Payoneer được hỗ trợ trên thiết bị nào?",
      suptitle: "Ứng dụng di động Payoneer hiện được hỗ trợ trên các thiết bị iOS và Android. Bạn có thể sử dụng các liên kết này để tải ứng dụng cho thiết bị của mình: iOS, Android.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "TTôi có thể thực hiện những thao tác nào với ứng dụng di động?",
      suptitle: " Ứng dụng di động Payoneer cho phép bạn dễ dàng quản lý tài khoản Payoneer của mình mọi lúc mọi nơi. Bạn có thể nhanh chóng kiểm tra tất cả số dư tài khoản hoặc thẻ, cũng như các giao dịch mới nhất của bạn, từ trang chủ của ứng dụng.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Làm cách nào để xem chi tiết và giao dịch cho một số dư cụ thể?",
      suptitle: "Từ Trang chủ, bấm vào bất kỳ tài khoản số dư nào của bạn để xem chi tiết số dư và các giao dịch mới nhất cho số dư đó. Để xem tất cả các giao dịch cho một số dư cụ thể, hãy nhấn Giao dịch trong menu và lọc theo số dư mong muốn.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Ứng dụng di động Payoneer được hỗ trợ trên thiết bị nào?",
      suptitle: "Ứng dụng di động Payoneer hiện được hỗ trợ trên các thiết bị iOS và Android. Bạn có thể sử dụng các liên kết này để tải ứng dụng cho thiết bị của mình: iOS, Android.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "TTôi có thể thực hiện những thao tác nào với ứng dụng di động?",
      suptitle: " Ứng dụng di động Payoneer cho phép bạn dễ dàng quản lý tài khoản Payoneer của mình mọi lúc mọi nơi. Bạn có thể nhanh chóng kiểm tra tất cả số dư tài khoản hoặc thẻ, cũng như các giao dịch mới nhất của bạn, từ trang chủ của ứng dụng.",
      time: "7: 52, July 25, 2024"),
  notificationModel(title: "Làm cách nào để xem chi tiết và giao dịch cho một số dư cụ thể?",
      suptitle: "Từ Trang chủ, bấm vào bất kỳ tài khoản số dư nào của bạn để xem chi tiết số dư và các giao dịch mới nhất cho số dư đó. Để xem tất cả các giao dịch cho một số dư cụ thể, hãy nhấn Giao dịch trong menu và lọc theo số dư mong muốn.",
      time: "7: 52, July 25, 2024"),
];